### ISSUE TITLE
Improve Search Area Request

### ISSUE THREAD

**Issue by MZober1993** [pnancke/trip-planner#58]
#29 should be replaced by a request with the given route on the saved db data

**Comment by MZober1993** [comment]
Todos:

1. create a List of BBoxes for the area of the route
2. create a Contains Statement (Closure) for a single BBoxes
3. combine all contains statements to one 
4. findAll POIs with the contains statement

**Comment by MZober1993** [comment]
route of leipzig taucha with this polygon: http://www.darrinward.com/lat-long/?id=2029632
and this result: http://www.darrinward.com/lat-long/?id=2029606
(same as with multiple requests)

**Comment by pnancke** [comment]
See: http://stackoverflow.com/questions/37882227/using-spatial-indexes-for-st-distance
