### ISSUE TITLE
OpenLayers createRegularPolygon draws Circle too small

### ISSUE THREAD

**Issue by pnancke** [pnancke/trip-planner#68]
`OpenLayers.Geometry.Polygon.createRegularPolygon(current_point, range, 50, 0);` draws the circle too small. The range always has to be 2/3 greater: `OpenLayers.Geometry.Polygon.createRegularPolygon(current_point, range * 1.66, 50, 0);`
This hotfix works until we found the reason for this.

**Comment by MZober1993** [comment]
@pnancke do you want to close this issue until we found the reason or until your PR to parallel routing is done?

**Comment by pnancke** [comment]
I'll close this issue when we found a better solution than increasing the wrong range.

**Comment by pnancke** [comment]
Closed because other issues have a higher priority and multiplying the range by 0.66 seems to be pretty accurate.
