### ISSUE TITLE
Fix End of Route SearchArea

### ISSUE THREAD

**Issue by MZober1993** [pnancke/trip-planner#74]
![bildschirmfoto_vom_2016-06-27_15_09_33](https://cloud.githubusercontent.com/assets/13154013/16380948/361fed32-3c7a-11e6-9228-8dfa755cdc69.png)

**Comment by pnancke** [comment]
See https://dev.mysql.com/doc/refman/5.6/en/spatial-operator-functions.html#function_st-union

**Comment by MZober1993** [comment]
fixed it:

![bildschirmfoto vom 2016-07-02 14 32 07](https://cloud.githubusercontent.com/assets/13154013/16540345/eda0011e-4061-11e6-9300-3081e1d401cd.png)
